security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://104.237.142.25:8080/oa/oauth/token
      userAuthorizationUri: http://104.237.142.25:8080/oa/oauth/authorize
      clientId: web
      clientSecret: appweb
    resource:
      #user-info-uri: http://localhost:4444/rest/init/me
      user-info-uri: http://104.237.142.25:8080/oa/rest/user/me
      #prefer-token-info: true
      #filter-order: 3
server:
  port: 4444
  context-path: /

logging:
  level:
    org.springframework.security: DEBUG

zuul:
  ignored-services: '*'
  routes:
    swagger-res:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      path: /swagger-resources/**
      url: http://104.237.142.25:4547/swagger-resources/
    swagger-api-docs:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      path: /v2/api-docs/**
      url: http://104.237.142.25:4547/v2/api-docs/
    swagger-webjars:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      path: /webjars/springfox-swagger-ui/**
      url: http://104.237.142.25:4547/webjars/springfox-swagger-ui/
    swagger:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      path: /swagger-ui.html
      url: http://104.237.142.25:4547/
    rest:
      path: /rest/**
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      url: http://104.237.142.25:4547/rest/
    oa:
      path: /logout
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      url: http://dev-codes.com:8080/logout
        