security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/oa/oauth/token
      userAuthorizationUri: http://localhost:8080/oa/oauth/authorize
      clientId: web
      clientSecret: appweb
    resource:
      #user-info-uri: http://localhost:4444/rest/init/me
      user-info-uri: http://localhost:8080/oa/rest/user/me
      #prefer-token-info: true
      #filter-order: 3
server:
  port: 4444
  context-path: /

logging:
  level:
    org.springframework.security: DEBUG

zuul:
  ignored-services: '*'
  routes:
    swagger:
      path: /swagger*/**
      url: http://localhost:4547/
    rest:
      path: /rest*/**
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      url: http://localhost:4547/