security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: https://orion-bike.com:8443/oa/oauth/token
      userAuthorizationUri: https://orion-bike.com:8443/oa/oauth/authorize
      clientId: web
      clientSecret: appweb
    resource:
      #user-info-uri: http://localhost:4444/rest/init/me
      user-info-uri: https://orion-bike.com:8443/oa/rest/user/me
      #prefer-token-info: true
      #filter-order: 3
server:
  port: 4444
  context-path: /

logging:
  level:
    org.springframework.security: DEBUG

zuul:
  ignored-services: '*'
  routes:
    swagger-res:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      path: /swagger-resources/**
      url: https://orion-bike.com:4443/swagger-resources/
    swagger-api-docs:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      path: /v2/api-docs/**
      url: https://orion-bike.com:4443/v2/api-docs/
    swagger-webjars:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      path: /webjars/springfox-swagger-ui/**
      url: https://orion-bike.com:4443/webjars/springfox-swagger-ui/
    swagger:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      path: /swagger-ui.html
      url: https://orion-bike.com:4443/
    rest:
      path: /rest/**
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      url: https://orion-bike.com:4443/rest/
    oa:
      path: /logout
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      url: https://orion-bike.com:8443/logout
    websocket:
      path: /websocket/**
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      url: https://orion-bike.com:4443/ 
        